name: CI

on:
  push:
    branches: ['main']
  pull_request:
    type: [opened, synchronize]

jobs:
  test:
    name: Test Node.js ${{ matrix.node-version }} on ${{ matrix.os }}

    strategy:
      matrix:
        # just run on ubuntu for now. will add mac and windows support later
        os: [ubuntu-latest]
        node-version: [16.x, 18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.13.5
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:unit
      - run: pnpm test:integration